<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="BTG704839" name="com.bt.og.testpages.CustomerPageTest" tests="4" failures="1" timestamp="03 Jan 2019 15:53:31 GMT" time="156.828" errors="0">
  <testcase name="test05_CustomerDetails" time="32.410" classname="com.bt.og.testpages.CustomerPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Customer not mactching expected [Naresh Kumars] but found [Naresh Kumar]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Customer not mactching expected [Naresh Kumars] but found [Naresh Kumar]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.bt.og.testpages.CustomerPageTest.test05_CustomerDetails(CustomerPageTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test05_CustomerDetails -->
  <testcase name="test05_CustomerDetails" time="34.404" classname="com.bt.og.testpages.CustomerPageTest">
    <skipped/>
  </testcase> <!-- test05_CustomerDetails -->
  <testcase name="test06_CustomerDetailsContinueButton" time="58.767" classname="com.bt.og.testpages.CustomerPageTest"/>
  <testcase name="test05_CustomerDetails" time="31.247" classname="com.bt.og.testpages.CustomerPageTest"/>
</testsuite> <!-- com.bt.og.testpages.CustomerPageTest -->
